# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WefoxPokedex' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WefoxPokedex
    # Pods for wfx
  pod 'R.swift'

  # Pods for Networking
  pod 'Alamofire'

  # Pods for Loging
  pod 'CocoaLumberjack/Swift'

  target 'WefoxPokedexTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
