# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WefoxPokedex' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WefoxPokedex
    # Pods for wfx
  pod 'R.swift', '~> 5.0.3'

  # Pods for Networking
  pod 'Alamofire', '~> 4.8.2'

  # Data Persistance
  pod 'RealmSwift', '~> 3.15.0'

  # Pods for Loging
  pod 'CocoaLumberjack/Swift', '~> 3.5.3'

  # Pods for UI
  pod 'SDWebImage', '~> 4.4.6'

  target 'WefoxPokedexTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
